version: "3"

services: 
    app:
        build: .
        image: examenraquel
        container_name: examenraquel
        ports: 
            - "7077:5000"
        volumes: 
            - ./src:/app